version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12.5-node
    working_directory: ~/repo
    environment:
      - TEST_OUTPUT_FILE: test.metrics
    steps:
      - checkout

      - run:
          name: Update package.json with latest tag
          # Replace the moot version in package.json with the latest git tag.
          # Note that we must preserve the > or circle will fail due to the colons being parsed as yaml.
          command: >
            sed -i "s|\"version\": \"0.0.0\"|\"version\": \"$(git describe --tags | cut -c 1- | awk -F \- '{print $1};')\"|g" package.json && cat package.json

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm run lint

      - run:
          name: Listen for metric emission
          command: nc -vv -ul -p 8125 > $TEST_OUTPUT_FILE 2>&1
          background: true

      - run:
          name: Run the metrics emitter
          command: node test/manual.js
          background: true

      - run:
          name: Wait for metrics output
          command: sleep 10

      - run:
          name: Show output and assert it's not none
          command: cat $TEST_OUTPUT_FILE && if [ ! -s "$TEST_OUTPUT_FILE" ]; then exit 1; fi

      - run:
          name: Assert relevant metrics were emitted
          command: grep "strigo_app_http_requests_total,env=prod,container_hostname=$HOSTNAME,tag=value:1|c" $TEST_OUTPUT_FILE

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
