version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run:
          command: nc -vv -ul -p 8125 > test.txt 2>&1
          background: true

      - run:
          command: node test/manual.js
          background: true

      - run: sleep 10
      - run: cat test.txt && if [ ! -s "test.txt" ]; then exit 1; fi
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
