version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    environment:
      - TEST_OUTPUT_FILE: test.metrics
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run:
          name: Listen for metric emission
          command: nc -vv -ul -p 8125 > $TEST_OUTPUT_FILE 2>&1
          background: true

      - run:
          name: Run the metrics emitter
          command: node test/manual.js
          background: true

      - run:
          name: Wait for metrics output
          command: sleep 10

      - run:
          name: Show output and assert it's not none
          command: cat $TEST_OUTPUT_FILE && if [ ! -s "$TEST_OUTPUT_FILE" ]; then exit 1; fi

      - run:
          name: Assert relevant metrics were emitted
          command: |
            # TODO: Check actual metric types and values
            grep "strigo_app_http_requests_total" $TEST_OUTPUT_FILE
            grep "strigo_app_my_gauge" $TEST_OUTPUT_FILE
            grep "strigo_app_my_histogram,tag=value" $TEST_OUTPUT_FILE
            grep "strigo_app_http_response_duration_ms" $TEST_OUTPUT_FILE

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
